import type { Excuse } from "@/types";

// Generate a date in the past
const getRandomDate = (daysAgo = 30) => {
  const date = new Date();
  date.setDate(date.getDate() - Math.floor(Math.random() * daysAgo));
  return date.toISOString();
};

// Mock data for excuses
export const excuses: Excuse[] = [
  {
    id: "excuse-17",
    text: "I lost track of time while watching cat videos.",
    category: "school",
    score: 21,
    createdAt: getRandomDate(18),
  },
  {
    id: "excuse-18",
    text: "I was stuck in traffic because of a parade for a fictional character.",
    category: "work",
    score: 30,
    createdAt: getRandomDate(17),
  },
  {
    id: "excuse-19",
    text: "My computer updated right before the deadline.",
    category: "work",
    score: 26,
    createdAt: getRandomDate(16),
  },
  {
    id: "excuse-20",
    text: "I was helping a friend move a couch up five flights of stairs.",
    category: "social",
    score: 18,
    createdAt: getRandomDate(19),
  },
  {
    id: "excuse-21",
    text: "My favorite team was playing in the finals and I lost track of time.",
    category: "social",
    score: 23,
    createdAt: getRandomDate(21),
  },
  {
    id: "excuse-39",
    text: "A squirrel stole my car keys and led me on a wild chase.",
    category: "work",
    score: 9,
    createdAt: getRandomDate(39),
  },
  {
    id: "excuse-40",
    text: "I was trapped in a revolving door for hours.",
    category: "social",
    score: 8,
    createdAt: getRandomDate(40),
  },
  {
    id: "excuse-41",
    text: "My shoes were abducted by a flock of geese.",
    category: "school",
    score: 7,
    createdAt: getRandomDate(41),
  },
  {
    id: "excuse-42",
    text: "I had to referee a thumb wrestling championship between my siblings.",
    category: "family",
    score: 10,
    createdAt: getRandomDate(42),
  },
  {
    id: "excuse-43",
    text: "My house was invaded by a marching band practicing for a parade.",
    category: "family",
    score: 11,
    createdAt: getRandomDate(43),
  },
  {
    id: "excuse-44",
    text: "I was busy teaching my plants how to photosynthesize.",
    category: "school",
    score: 8,
    createdAt: getRandomDate(44),
  },
  {
    id: "excuse-45",
    text: "My reflection challenged me to a staring contest and I lost track of time.",
    category: "work",
    score: 12,
    createdAt: getRandomDate(45),
  },
  {
    id: "excuse-46",
    text: "I was stuck in a hammock and couldn't escape.",
    category: "social",
    score: 13,
    createdAt: getRandomDate(46),
  },
  {
    id: "excuse-47",
    text: "My neighbor's parrot kept mimicking my alarm and confused me.",
    category: "family",
    score: 9,
    createdAt: getRandomDate(47),
  },
  {
    id: "excuse-48",
    text: "I was busy decoding a secret message from my cereal.",
    category: "school",
    score: 10,
    createdAt: getRandomDate(48),
  },
  {
    id: "excuse-49",
    text: "I was waiting for my toast to pop up and it never did.",
    category: "work",
    score: 7,
    createdAt: getRandomDate(49),
  },
  {
    id: "excuse-50",
    text: "My pet turtle hid my homework under its shell.",
    category: "school",
    score: 11,
    createdAt: getRandomDate(50),
  },
  {
    id: "excuse-51",
    text: "I was caught in a time loop and kept reliving the same hour.",
    category: "work",
    score: 13,
    createdAt: getRandomDate(51),
  },
  {
    id: "excuse-52",
    text: "My imaginary friend scheduled a surprise party for me.",
    category: "social",
    score: 8,
    createdAt: getRandomDate(52),
  },
  {
    id: "excuse-53",
    text: "I was translating my thoughts into whale song.",
    category: "school",
    score: 9,
    createdAt: getRandomDate(53),
  },
  {
    id: "excuse-54",
    text: "My socks formed a union and went on strike.",
    category: "family",
    score: 10,
    createdAt: getRandomDate(54),
  },
  {
    id: "excuse-55",
    text: "I was busy negotiating peace between my two goldfish.",
    category: "family",
    score: 12,
    createdAt: getRandomDate(55),
  },
  {
    id: "excuse-56",
    text: "I was stuck in a virtual reality game and couldn't log out.",
    category: "work",
    score: 14,
    createdAt: getRandomDate(56),
  },
  {
    id: "excuse-57",
    text: "My shadow refused to follow me today.",
    category: "school",
    score: 8,
    createdAt: getRandomDate(57),
  },
  {
    id: "excuse-58",
    text: "I was busy teaching my goldfish how to fetch.",
    category: "family",
    score: 11,
    createdAt: getRandomDate(58),
  },
  {
    id: "excuse-59",
    text: "Aliens borrowed my phone to call home and erased my calendar.",
    category: "work",
    score: 15,
    createdAt: getRandomDate(59),
  },
  {
    id: "excuse-60",
    text: "I was busy untangling spaghetti that tied my shoes together.",
    category: "school",
    score: 10,
    createdAt: getRandomDate(60),
  },
  {
    id: "excuse-61",
    text: "My coffee mug ran away with my motivation.",
    category: "work",
    score: 13,
    createdAt: getRandomDate(61),
  },
  {
    id: "excuse-62",
    text: "I had to babysit my neighbor's invisible dog.",
    category: "family",
    score: 9,
    createdAt: getRandomDate(62),
  },
  {
    id: "excuse-63",
    text: "A wizard turned my alarm clock into a frog.",
    category: "school",
    score: 14,
    createdAt: getRandomDate(63),
  },
  {
    id: "excuse-64",
    text: "I was stuck in a staring contest with my goldfish.",
    category: "family",
    score: 8,
    createdAt: getRandomDate(64),
  },
  {
    id: "excuse-65",
    text: "My shoes decided to walk themselves to the park.",
    category: "social",
    score: 12,
    createdAt: getRandomDate(65),
  },
  {
    id: "excuse-66",
    text: "I was busy chasing a rainbow for the pot of gold.",
    category: "work",
    score: 11,
    createdAt: getRandomDate(66),
  },
  {
    id: "excuse-67",
    text: "My homework was eaten by a time-traveling dinosaur.",
    category: "school",
    score: 16,
    createdAt: getRandomDate(67),
  },
  {
    id: "excuse-68",
    text: "I was translating my essay into Klingon.",
    category: "school",
    score: 10,
    createdAt: getRandomDate(68),
  },
  {
    id: "excuse-69",
    text: "My neighbor's WiFi interfered with my thoughts.",
    category: "work",
    score: 9,
    createdAt: getRandomDate(69),
  },
  {
    id: "excuse-70",
    text: "I was busy teaching my cat to use the remote.",
    category: "family",
    score: 12,
    createdAt: getRandomDate(70),
  },
  {
    id: "excuse-71",
    text: "My socks shrank and I couldn't walk properly.",
    category: "social",
    score: 8,
    createdAt: getRandomDate(71),
  },
  {
    id: "excuse-72",
    text: "A magician made my keys disappear.",
    category: "work",
    score: 13,
    createdAt: getRandomDate(72),
  },
  {
    id: "excuse-73",
    text: "I was busy counting the number of tiles on my ceiling.",
    category: "school",
    score: 7,
    createdAt: getRandomDate(73),
  },
  {
    id: "excuse-74",
    text: "My calendar switched to a different time zone.",
    category: "work",
    score: 10,
    createdAt: getRandomDate(74),
  },
  {
    id: "excuse-75",
    text: "I was abducted by garden gnomes for a tea party.",
    category: "social",
    score: 14,
    createdAt: getRandomDate(75),
  },
  {
    id: "excuse-76",
    text: "My reflection started giving me life advice.",
    category: "family",
    score: 11,
    createdAt: getRandomDate(76),
  },
  {
    id: "excuse-77",
    text: "I was busy alphabetizing my soup noodles.",
    category: "school",
    score: 9,
    createdAt: getRandomDate(77),
  },
  {
    id: "excuse-78",
    text: "A parade of ducks blocked my driveway.",
    category: "work",
    score: 12,
    createdAt: getRandomDate(78),
  },
];
